services:
    database:
        image: pgvector/pgvector:pg18
        container_name: ac-computers-db
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: ac_computers_db
        ports:
            - 5432:5432
        volumes:
            - ac-computers-postgres-volume:/var/lib/postgresql
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/01-init-vector.sql:ro

volumes:
    ac-computers-postgres-volume:
